<a href="https://colab.research.google.com/github/onism/MyLearning/blob/master/Preprocessing_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mean Removal

“This helps us in removing any bias from the features. ”

摘录来自: Prateek Joshi. “Python: Real World Machine Learning。” Apple Books. 

In [1]:
import numpy as np 
from sklearn import preprocessing  

data = np.array([
                 [3,1.5,2,-5.4],
                 [0,4,-0.3,2.1],
                 [1,3.3,-1.9, -4.3]
])

data_standardized = preprocessing.scale(data)
print('Mean', data_standardized.mean(axis=0))
print('Std', data_standardized.std(axis=0))

Mean [ 5.55111512e-17 -2.77555756e-16 -7.40148683e-17 -7.40148683e-17]
Std [1. 1. 1. 1.]


# Scaling



In [2]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print(data_scaled)

[[1.         0.         1.         0.        ]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.72       0.         0.14666667]]


#Binarization

“Binarization is used when you want to convert your numerical feature vector into a Boolean vector.”

摘录来自: Prateek Joshi. “Python: Real World Machine Learning。” Apple Books. 

In [3]:
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print(data_binarized)

[[1. 1. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]


# One Hot Encoding

In [4]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0,2,1,12], [1,3,5,3], [2,3,2,12], [1,2,4,3]])
encoded_vector = encoder.transform([[2,3,5,3]]).toarray() 
print(encoded_vector)

[[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]


# Label encoding

In [5]:
label_encoder = preprocessing.LabelEncoder()
input_classes = ['audi', 'ford', 'audi', 'toyota', 'ford', 'bmw']
label_encoder.fit(input_classes)
for i, item in enumerate(label_encoder.classes_):
    print(item, '--->', i)

audi ---> 0
bmw ---> 1
ford ---> 2
toyota ---> 3


In [6]:
labels = ['toyota', 'ford', 'audi']
encoded_labels = label_encoder.transform(labels)
print(encoded_labels)

[3 2 0]


In [7]:
encoded_labels = [2,1,0,3,2]
decoded_labels = label_encoder.inverse_transform(encoded_labels)
print(decoded_labels)

['ford' 'bmw' 'audi' 'toyota' 'ford']
